os: linux
dist: trusty
sudo: required
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 8
install:
  - yarn install --ignore-engines --check-files --frozen-lockfile
script:
  - yarn run prepublishOnly
after_success:
  - npm run codecov
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
