// flow-typed signature: 2f17b533fd5d82ed16da4a9ea5e14eca
// flow-typed version: <<STUB>>/babel-preset-react_v^6.16.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react/lib' {
  declare module.exports: any
}

// Filename aliases
declare module 'babel-preset-react/lib/index' {
  declare module.exports: $Exports<'babel-preset-react/lib'>
}
declare module 'babel-preset-react/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-react/lib'>
}
