// flow-typed signature: dc6de9e0f36c16afc92787da5a728582
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config-react_v^3.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@jedwards1211/eslint-config-react/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-react'>;
}
declare module '@jedwards1211/eslint-config-react/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-react'>;
}
